[package]
name = "swaston-rust"
version = "0.1.0"
authors = ["Wirtos <Wirtos.new@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-segmentation = "1.3.0"
itertools = "0.8.0"